config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :home, only: :index
  resources :users
  get 'users/new/teacher' => 'users#new_teacher'
  get 'users/edit/:id/teacher' => 'users#edit_teacher'

  # Authentication
  namespace :auth do
    post '' => 'user_sessions#create'
    get 'login' => 'user_sessions#new'
    delete 'logout' => 'user_sessions#destroy'
  end

  resources :chapters
  resources :lectures
  resources :homeworks
  resources :submissions
  resources :lecture_students
  resources :questions
  resources :question_points
  resources :answers
  resources :answer_points
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_one :answer_point, dependent: :destroy
  # 本当は teacher or student と紐づくが、双方にNotNull制約を入れていないため、ちゃんとバリデーションかけてあげること！
end

app/models/answer_point.rb
class AnswerPoint < ApplicationRecord
  belongs_to :answer
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :lecture
  has_many :homework, dependent: :destroy
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :chapter
  has_many :submissions, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :teacher
  has_many :chapters, dependent: :destroy
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :student
  belongs_to :lecture
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :homework
  belongs_to :student
  has_one :question_point, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/models/question_point.rb
class QuestionPoint < ApplicationRecord
  belongs_to :question
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :user
  has_many :lecture_students, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :homework
  belongs_to :student
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  belongs_to :user
  has_many :lectures, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

  # TODO: dependentの取り扱いを検討する
  has_one :teacher, dependent: :destroy
  has_one :student, dependent: :destroy
  accepts_nested_attributes_for :teacher
  accepts_nested_attributes_for :student

  validates :email,
            format: {
              with: /@/,
              message: 'should look like an email address.'
            },
            length: { maximum: 100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_email?
            }

  validates :password,
            confirmation: { if: :require_password? },
            length: {
              minimum: 8,
              if: :require_password?
            }

  validates :password_confirmation,
            length: {
              minimum: 8,
              if: :require_password?
            }
end

app/models/user_session.rb
# frozen_string_literal: true

class UserSession < Authlogic::Session::Base
  secure Rails.env.production?
  httponly true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.all
    @teacher = Teacher.find_by_user_id(current_user.id)
    @student = Student.find_by_user_id(current_user.id)
  end

  def new
    @question = Question.new
  end

  def create
    homework_id = params[:question][:homework_id]
    student_id = params[:question][:student_id]
    title = params[:question][:title]
    body = params[:question][:body]
    file_uri = params[:question][:file_uri]
    like_count = params[:question][:like_count]
    solved_at = params[:question][:solved_at]
    @question =Question.create(homework_id: homework_id, student_id: student_id, title: title, body: body,file_uri: file_uri,like_count: like_count,solved_at: solved_at)
    if @question.save
      #saveが完了したら、一覧ページへリダイレクト
      redirect_to '/questions'
    else
      #saveを失敗すると新規作成ページへ
      render 'new'
    end
  end

  def edit
  @question = Question.find(params[:id])
  end

  #update->編集のアップデート
  def update
    homework_id = params[:question][:homework_id]
    student_id = params[:question][:student_id]
    title = params[:question][:title]
    body = params[:question][:body]
    file_uri = params[:question][:file_uri]
    like_count = params[:question][:like_count]
    solved_at = params[:question][:solved_at]
    question = Question.find(params[:id])
    question.update(homework_id: homework_id, student_id: student_id, title: title, body: body,file_uri: file_uri,like_count: like_count,solved_at: solved_at)

      redirect_to '/questions'

  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    #一覧ページへリダイレクト
    redirect_to '/questions'
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/lectuers_helper.rb
module LectuersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/questions/edit.html.erb
<%= form_for @question , url: {action: :update} do |f| %>
<p>
    <p><%= f.label :homework_id, '課題ID' %></p>
    <%= f.text_field :homework_id %>
</p>
<p>
    <p><%= f.label :student_id, '生徒ID' %></p>
    <%= f.text_field :student_id %>
</p>
<p>
    <p><%= f.label :title, 'タイトル' %></p>
    <%= f.text_field :title %>
</p>
<p>
    <p><%= f.label :body, '本文' %></p>
    <%= f.text_field :body %>
</p>
<p>
   <p><%= f.label :file_uri, 'ファイル' %></p>
    <%= f.text_field :file_uri %> 
</p>
<p>
    <p><%= f.label :like_count, 'like_count' %></p>
    <%= f.text_field :like_count %>
</p>
<p>
    <p><%= f.label :solved_at, '解決した日' %></p>
    <%= f.date_field :solved_at %>
</p>
<p>
    <%= f.submit '登録' %>    
</p>

<% end %>

app/views/questions/index.html.erb
<h1 class="page-title">最近投稿された質問</h1>
<table class="list">
  <tr class="list-header">
    <td>ID</td>
    <td>課題ID</td>
    <td>学生ID</td>
    <td>タイトル</td>
    <td>投稿日</td>
    <td>　</td>
  </tr>
  <% @question.each do |question| %>
  <tr class="list-content">
    <td><%= question.id %></td>
    <td><%= question.homework_id %></td>
    <td><%= question.student_id %></td>
    <td><%= question.title %></td>
    <td><%= question.created_at %></td>
    <td>
      <%= link_to '詳細', "questions/#{question.id}" %>　
      <%= link_to '削除', "questions/#{question.id}",method: :delete %>　
      <%= link_to '編集', "questions/#{question.id}/edit" %>　
    </td>
  </tr>
  <% end %>
</table>
<%= link_to'新規追加','questions/new' , class: 'main-button'%>

app/views/questions/new.html.erb
<%= form_for @question , url: {action: :create} do |f| %>
<p>
    <p><%= f.label :homework_id, '課題ID' %></p>
    <%= f.text_field :homework_id %>
</p>
<p>
    <p><%= f.label :student_id, '生徒ID' %></p>
    <%= f.text_field :student_id %>
</p>
<p>
    <p><%= f.label :title, 'タイトル' %></p>
    <%= f.text_field :title %>
</p>
<p>
    <p><%= f.label :body, '本文' %></p>
    <%= f.text_field :body %>
</p>
<p>
   <p><%= f.label :file_uri, 'ファイル' %></p>
    <%= f.text_field :file_uri %> 
</p>
<p>
    <p><%= f.label :like_count, 'like_count' %></p>
    <%= f.text_field :like_count %>
</p>
<p>
    <p><%= f.label :solved_at, '解決した日' %></p>
    <%= f.date_field :solved_at %>
</p>
<p>
    <%= f.submit '登録' %>
</p>
<% end %>

app/views/questions/show.html.erb
<h1 class="page-title">質問詳細（課題ID：<%= @question.homework_id %>）</h1>
<ul class="show first">
  <li>課題ID</li>
  <li><%= @question.homework_id %></li>
</ul>
<ul class="show">
  <li>生徒ID</li>
  <li><%= @question.student_id %></li>
</ul>
<ul class="show">
  <li>質問タイトル</li>
  <li><%= @question.title %></li>
</ul>
<ul class="show">
  <li>質問の本文</li>
  <li><%= @question.body %></li>
</ul>
<ul class="show">
  <li>添付ファイル</li>
  <li><%= @question.file_uri %></li>
</ul>
<ul class="show">
  <li>私もわからん🙋‍️</li>
  <li>0</li>
</ul>
<ul class="show">
  <li>解決した日</li>
  <li><%= @question.solved_at %></li>
</ul>

<h1 class="page-title">これまでの回答</h1>
<table class="list">
  <tr class="list-header">
    <td>投稿者</td>
    <td>内容</td>
    <td>投稿日</td>
  </tr>
  <% @answers.each do |answer| %>
    <tr class="list-content">
      <td><%= answer.teacher_id if @teacher.present? %><%= answer.student_id if @student.present? %></td>
      <td><%= answer.body %></td>
      <td><%= answer.created_at %></td>
    </tr>
  <% end %>
</table>

<%= link_to '回答する',new_answer_path(question_id: @question.id), class: 'main-button' %>
<%= link_to 'もどる', '/questions' , class: 'main-button' %>