config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :home, only: :index
  resources :users
  get 'users/new/teacher' => 'users#new_teacher'
  get 'users/edit/:id/teacher' => 'users#edit_teacher'

  # Authentication
  namespace :auth do
    post '' => 'user_sessions#create'
    get 'login' => 'user_sessions#new'
    delete 'logout' => 'user_sessions#destroy'
  end

  resources :chapters
  resources :lectures
  resources :homeworks
  resources :submissions
  resources :lecture_students
  resources :questions
  resources :question_points
  resources :answers
  resources :answer_points
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_one :answer_point, dependent: :destroy
  # 本当は teacher or student と紐づくが、双方にNotNull制約を入れていないため、ちゃんとバリデーションかけてあげること！
end

app/models/answer_point.rb
class AnswerPoint < ApplicationRecord
  belongs_to :answer
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :lecture
  has_many :homework, dependent: :destroy
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :chapter
  has_many :submissions, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :teacher
  has_many :chapters, dependent: :destroy
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :student
  belongs_to :lecture
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :homework
  belongs_to :student
  has_one :question_point, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/models/question_point.rb
class QuestionPoint < ApplicationRecord
  belongs_to :question
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :user
  has_many :lecture_students, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :homework
  belongs_to :student
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  belongs_to :user
  has_many :lectures, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

  # TODO: dependentの取り扱いを検討する
  has_one :teacher, dependent: :destroy
  has_one :student, dependent: :destroy
  accepts_nested_attributes_for :teacher
  accepts_nested_attributes_for :student

  validates :email,
            format: {
              with: /@/,
              message: 'should look like an email address.'
            },
            length: { maximum: 100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_email?
            }

  validates :password,
            confirmation: { if: :require_password? },
            length: {
              minimum: 8,
              if: :require_password?
            }

  validates :password_confirmation,
            length: {
              minimum: 8,
              if: :require_password?
            }
end

app/models/user_session.rb
# frozen_string_literal: true

class UserSession < Authlogic::Session::Base
  secure Rails.env.production?
  httponly true
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

  def index
    @lecture = Lecture.all.order(:id)
    @teacher = Teacher.find_by_user_id(current_user.id)
  end

  def show
    @lecture = Lecture.find(params[:id])
    @teacher = Teacher.find_by_user_id(current_user.id)
    @chapter = Chapter.where(lecture_id: params[:id])
  end

  def new
    @lecture = Lecture.new
  end

  def create
    teacher = Teacher.find_by_user_id(current_user.id)
    # teacher_id = params[:lecture][:teacher_id]
    teacher_id = teacher.id
    name = params[:lecture][:name]
    note = params[:lecture][:note]
    question_point = params[:lecture][:question_point]
    answer_point = params[:lecture][:answer_point]
    @lecture =Lecture.create(teacher_id: teacher_id, name: name, note: note, question_point: question_point, answer_point: answer_point)
    if @lecture.save
      #saveが完了したら、一覧ページへリダイレクト
      redirect_to '/lectures'
    else
      #saveを失敗すると新規作成ページへ
      render 'new'
    end
  end

  def edit
  @lecture = Lecture.find(params[:id])
  end

  #update->編集のアップデート
  def update
    teacher_id = params[:lecture][:teacher_id]
    name = params[:lecture][:name]
    note = params[:lecture][:note]
    question_point = params[:lecture][:question_point]
    answer_point = params[:lecture][:answer_point]
    lecture = Lecture.find(params[:id])
    lecture.update(teacher_id: teacher_id, name: name, note: note, question_point: question_point, answer_point: answer_point)

      redirect_to '/lectures'

  end

  def destroy
    lecture = Lecture.find(params[:id])
    lecture.destroy
    #一覧ページへリダイレクト
    redirect_to '/lectures'
  end
  
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/lectuers_helper.rb
module LectuersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/lectures/edit.html.erb
<%= form_for @lecture , url: {action: :update} do |f| %>
<p>
    <%= f.label :teacher_id, '教師ID' %>
    <%= f.text_field :teacher_id %>
</p>
<p>
    <%= f.label :name, '講義名' %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :note, 'note' %>
    <%= f.text_field :note %>
</p>
<p>
   <%= f.label :question_point, '質問点' %>
    <%= f.text_field :question_point %> 
</p>
<p>
    <%= f.label :answer_point, '回答点' %>
    <%= f.text_field :answer_point %>
</p>
<p>
    <%= f.submit '登録' %>    
</p>

<% end %>

app/views/lectures/index.html.erb
<div class="lectures">
  <h1 class="page-title">担当講義一覧</h1>
  <% if @teacher.present? %>
    <table class="list">
      <tr class="list-header">
        <td>　</td>
        <td>ID</td>
        <td>講義名</td>
        <td>備考</td>
        <td>　</td>
      </tr>
      <% @lecture.each do |lecture| %>
        <tr class="list-content">
          <td class="center"><%= link_to '🔍', "lectures/#{lecture.id}" %></td>
          <td><%= lecture.id %></td>
          <td><%= lecture.name %></td>
          <td><%= lecture.note %></td>
          <td class="right">
            <%= link_to '削除', "lectures/#{lecture.id}",method: :delete %>　
            <%= link_to '編集', "lectures/#{lecture.id}/edit" %>　
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <% if @teacher.present? %>
    <%= link_to '新規追加', new_lecture_path, class: 'main-button' %>
  <% end %>
</div>

app/views/lectures/new.html.erb
<%= form_for @lecture , url: {action: :create} do |f| %>
<%#<p>
<%#    <%= f.label :teacher_id, '教師ID' %>
<%#    <%= f.text_field :teacher_id %>
<p>
    <%= f.label :name, '講義名' %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :note, 'note' %>
    <%= f.text_field :note %>
</p>
<p>
   <%= f.label :question_point, '質問点' %>
    <%= f.text_field :question_point %> 
</p>
<p>
    <%= f.label :answer_point, '回答点' %>
    <%= f.text_field :answer_point %>
</p>
<p>
    <%= f.submit '登録' %>
</p>
<%= link_to 'Back', :back %>
<% end %>

app/views/lectures/show.html.erb
<h1 class="page-title">講義：<%= @lecture.name %></h1>
<div class="lecture-show-wrapper">
  <ul class="lecture-show first">
    <li>教師ID</li>
    <li><%= @lecture.teacher_id %></li>
  </ul>
  <ul class="lecture-show">
    <li>講義ID</li>
    <li><%= @lecture.id %></li>
  </ul>
  <ul class="lecture-show">
    <li>講義名</li>
    <li><%= @lecture.name %></li>
  </ul>
  <ul class="lecture-show">
    <li>備考</li>
    <li><%= @lecture.note %></li>
  </ul>
  <ul class="lecture-show">
    <li>質問点</li>
    <li><%= @lecture.question_point %></li>
  </ul>
  <ul class="lecture-show">
    <li>回答点</li>
    <li><%= @lecture.answer_point %></li>
  </ul>
</div>

<% if @chapter.present? %>
  <table class="list">
    <tr class="list-header">
      <td>講義回数</td>
      <td>タイトル</td>
      <td>備考</td>
      <td>　</td>
    </tr>
    <% @chapter.each do |chapter| %>
      <tr class="list-content">
        <td><%= chapter.chapter_no %></td>
        <td><%= chapter.title %></td>
        <td><%= chapter.note %></td>
        <td class="right">
          <%= link_to '表示', "/chapters/#{chapter.id}" %>　
          <%= link_to '削除', "/chapters/#{chapter.id}",method: :delete %>　
          <%= link_to '編集', "/chapters/#{chapter.id}/edit" %>　
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<% if @teacher.present? %>
  <p><%= link_to'講義回数を追加',new_chapter_path(lecture_id: @lecture.id), class: 'main-button'  %></p>
<% end %>

<%= link_to '講義一覧に戻る', '/lectures', class: 'main-button' %>