config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :home, only: :index
  resources :users
  get 'users/new/teacher' => 'users#new_teacher'
  get 'users/edit/:id/teacher' => 'users#edit_teacher'

  # Authentication
  namespace :auth do
    post '' => 'user_sessions#create'
    get 'login' => 'user_sessions#new'
    delete 'logout' => 'user_sessions#destroy'
  end

  resources :chapters
  resources :lectures
  resources :homeworks
  resources :submissions
  resources :lecture_students
  resources :questions
  resources :question_points
  resources :answers
  resources :answer_points
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_one :answer_point, dependent: :destroy
  # 本当は teacher or student と紐づくが、双方にNotNull制約を入れていないため、ちゃんとバリデーションかけてあげること！
end

app/models/answer_point.rb
class AnswerPoint < ApplicationRecord
  belongs_to :answer
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :lecture
  has_many :homework, dependent: :destroy
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :chapter
  has_many :submissions, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :teacher
  has_many :chapters, dependent: :destroy
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :student
  belongs_to :lecture
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :homework
  belongs_to :student
  has_one :question_point, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/models/question_point.rb
class QuestionPoint < ApplicationRecord
  belongs_to :question
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :user
  has_many :lecture_students, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :homework
  belongs_to :student
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  belongs_to :user
  has_many :lectures, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

  # TODO: dependentの取り扱いを検討する
  has_one :teacher, dependent: :destroy
  has_one :student, dependent: :destroy
  accepts_nested_attributes_for :teacher
  accepts_nested_attributes_for :student

  validates :email,
            format: {
              with: /@/,
              message: 'should look like an email address.'
            },
            length: { maximum: 100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_email?
            }

  validates :password,
            confirmation: { if: :require_password? },
            length: {
              minimum: 8,
              if: :require_password?
            }

  validates :password_confirmation,
            length: {
              minimum: 8,
              if: :require_password?
            }
end

app/models/user_session.rb
# frozen_string_literal: true

class UserSession < Authlogic::Session::Base
  secure Rails.env.production?
  httponly true
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    
  def index
    @chapter = Chapter.all.order(:id)
    @teacher = Teacher.find_by_user_id(current_user.id)
  end

  def show
    @chapter = Chapter.find(params[:id])
    @lecture = Lecture.find_by_id(@chapter.lecture_id)
    @teacher = Teacher.find_by_user_id(current_user.id)
    @student = Student.find_by_user_id(current_user.id)
    @homework = Homework.where(chapter_id: params[:id])
  end

  def new
    @chapter = Chapter.new
    @lecture_id = params[:lecture_id]
  end

  def create
    lecture_id = params[:chapter][:lecture_id]
    chapter_no = params[:chapter][:chapter_no]
    title = params[:chapter][:title]
    note = params[:chapter][:note]
    first_chapter_no = params[:first_chapter_no]
    first_chapter_no.to_i.upto(chapter_no.to_i) do |num|
      @chapter =Chapter.create(lecture_id: lecture_id, chapter_no: num, title: title, note: note)
    end
        if @chapter.save
           #saveが完了したら、一覧ページへリダイレクト
          redirect_to '/chapters'
        else
          #saveを失敗すると新規作成ページへ
           render 'new'
        end
  end

  def edit
  @chapter = Chapter.find(params[:id])
  end

  #update->編集のアップデート
  def update
    lecture_id = params[:chapter][:lecture_id]
    chapter_no = params[:chapter][:chapter_no]
    title = params[:chapter][:title]
    note = params[:chapter][:note]
    chapter = Chapter.find(params[:id])
    chapter.update(lecture_id: lecture_id, chapter_no: chapter_no, title: title, note: note)

      redirect_to '/chapters'

  end

  def destroy
    chapter = Chapter.find(params[:id])
    chapter.destroy
    #一覧ページへリダイレクト
    redirect_to '/chapters'
  end
  
 
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/lectuers_helper.rb
module LectuersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/chapters/edit.html.erb
<%= form_for @chapter , url: {action: :update} do |f| %>
<p>
    <%= f.label :lecture_id, 'lecture ID' %>
    <%= f.text_field :lecture_id %>
</p>
<p>
    <%= f.label :chapter_no, 'chapter NO.' %>
    <%= f.text_field :chapter_no %>
</p>
<p>
    <%= f.label :note, 'note' %>
    <%= f.text_field :note %>
</p>
<p>
   <%= f.label :title, 'title' %>
    <%= f.text_field :title %> 
</p>
<p>
    <%= f.submit '登録' %>    
</p>

<% end %>

app/views/chapters/index.html.erb
<h1 class="page-title">講義一覧(全15回)</h1>
<table class="list">
  <tr class="list-header">
    <td>講義名</td>
    <td>講義回数</td>
    <td>タイトル</td>
    <td>備考</td>
    <td>　</td>
  </tr>
  <% @chapter.each do |chapter| %>
    <tr class="list-content">
      <td><%= Lecture.find_by(id: chapter.lecture_id).name %></td>
      <td><%= chapter.chapter_no %></td>
      <td><%= chapter.title %></td>
      <td><%= chapter.note %></td>
      <td class="right">
        <%= link_to '表示', "chapters/#{chapter.id}" %>　
        <%= link_to '削除', "chapters/#{chapter.id}",method: :delete %>　
        <%= link_to '編集', "chapters/#{chapter.id}/edit" %>　
      </td>
    </tr>
  <% end %>
</table>
<p><%= link_to '講義を追加','chapters/new', class: 'main-button'%></p>

app/views/chapters/new.html.erb
<%= form_for @chapter , url: {action: :create} do |f| %>
<p>
    <%= f.label :lecture_id, 'lecture ID' %>
    <%= f.text_field :lecture_id ,value: @lecture_id%>
</p>
<p>
    <%= label_tag :first_chapter_no, 'first_chapter NO.' %>
    <%= text_field_tag :first_chapter_no %>
</p>
<p>
    <%= f.label :chapter_no, 'last_chapter NO.' %>
    <%= f.text_field :chapter_no %>
</p>
<p>
    <%= f.label :note, 'note' %>
    <%= f.text_field :note %>
</p>
<p>
   <%= f.label :title, 'title' %>
    <%= f.text_field :title %> 
</p>
<p>
    <%= f.submit '登録' %>
</p>
<% end %>

app/views/chapters/show.html.erb
<h1 class="page-title"><%= @lecture.name %> 第<%= @chapter.chapter_no %>回</h1>
<ul class="show first">
  <li>講義回数</li>
  <li><%= @chapter.chapter_no %></li>
</ul>
<ul class="show">
  <li>タイトル</li>
  <li><%= @chapter.title %></li>
</ul>
<ul class="show">
  <li>備考</li>
  <li><%= @chapter.note %></li>
</ul>

<%# if @student.present? %>
<!--<h1 class="page-title">今回の課題</h1>-->
  <%# @homework.each do |homework| %>
<!--    <ul class="show first">-->
<!--      <li>課題ID</li>-->
<!--      <li><%#= homework.id %></li>-->
<!--    </ul>-->
<!--    <ul class="show first">-->
<!--      <li>課題タイトル</li>-->
<!--      <li><%#= link_to "#{homework.title}", "../homeworks/#{homework.id}" %></li>-->
<!--    </ul>-->
  <%# end %>
<%# end %>

<% if @teacher.present? %>
  <% @homework.each do |homework| %>
    <h1 class="page-title">今回の課題</h1>
    <% @homework.each do |homework| %>
      <ul class="show first">
        <li>課題ID</li>
        <li><%= homework.id %></li>
      </ul>
      <ul class="show">
        <li>課題タイトル</li>
        <li><%= link_to "#{homework.title}", "../homeworks/#{homework.id}" %></li>
      </ul>
    <% end %>
  <% end %>

  <%= link_to'課題新規追加',new_homework_path(chapter_id: @chapter.id), class: 'main-button' %>
<% end %>
<%= link_to '講義ページにもどる', "/lectures/#{@lecture.id}", class: 'main-button'%>