config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :home, only: :index
  resources :users
  get 'users/new/teacher' => 'users#new_teacher'
  get 'users/edit/:id/teacher' => 'users#edit_teacher'

  # Authentication
  namespace :auth do
    post '' => 'user_sessions#create'
    get 'login' => 'user_sessions#new'
    delete 'logout' => 'user_sessions#destroy'
  end

  resources :chapters
  resources :lectures
  resources :homeworks
  resources :submissions
  resources :lecture_students
  resources :questions
  resources :question_points
  resources :answers
  resources :answer_points
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_one :answer_point, dependent: :destroy
  # 本当は teacher or student と紐づくが、双方にNotNull制約を入れていないため、ちゃんとバリデーションかけてあげること！
end

app/models/answer_point.rb
class AnswerPoint < ApplicationRecord
  belongs_to :answer
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :lecture
  has_many :homework, dependent: :destroy
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :chapter
  has_many :submissions, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :teacher
  has_many :chapters, dependent: :destroy
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :student
  belongs_to :lecture
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :homework
  belongs_to :student
  has_one :question_point, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/models/question_point.rb
class QuestionPoint < ApplicationRecord
  belongs_to :question
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :user
  has_many :lecture_students, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :homework
  belongs_to :student
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  belongs_to :user
  has_many :lectures, dependent: :destroy

  def self.is_logged_in?(user_id)
    return false if find_by(user_id: user_id).nil?

    true
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
  end

  # TODO: dependentの取り扱いを検討する
  has_one :teacher, dependent: :destroy
  has_one :student, dependent: :destroy
  accepts_nested_attributes_for :teacher
  accepts_nested_attributes_for :student

  validates :email,
            format: {
              with: /@/,
              message: 'should look like an email address.'
            },
            length: { maximum: 100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_email?
            }

  validates :password,
            confirmation: { if: :require_password? },
            length: {
              minimum: 8,
              if: :require_password?
            }

  validates :password_confirmation,
            length: {
              minimum: 8,
              if: :require_password?
            }
end

app/models/user_session.rb
# frozen_string_literal: true

class UserSession < Authlogic::Session::Base
  secure Rails.env.production?
  httponly true
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/lectuers_helper.rb
module LectuersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div class="navigation">
  <ul>
    <li><%= link_to 'QLearning', '/' %></li>
  </ul>
  <ul>
    <% if current_user.nil? %>
      <li><%= link_to 'ログイン/新規登録', auth_login_path %></li>
    <% elsif Teacher.find_by(user_id: current_user.id)  %>
      <li><%= link_to '講義一覧', lectures_path %></li>
      <li><%= link_to '直近の質問一覧', questions_path %></li>
      <li><%= link_to 'ログアウト', "/auth/logout", method: :delete %></li>
    <% elsif Student.find_by(user_id: current_user.id)  %>
      <li><%= link_to '講義一覧', lectures_path %></li>
      <li><%= link_to '課題一覧', homeworks_path %></li>
      <li><%= link_to '自分の質問', questions_path %></li>
      <li><%= link_to 'ログアウト', "/auth/logout", method: :delete %></li>
    <% else %>
      <li><%= link_to 'ログイン/新規登録', auth_login_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qlearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://unpkg.com/ress/dist/ress.min.css' %>
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.9.0/css/all.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,500,700&display=swap' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "layouts/navigation" %>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>